language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  
before_script:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - phpcs --config-set default_standard PEAR

script: 
  - phpcs --standard=build/travis-ci-phpcs.xml --extensions=php --ignore=vendor
  - phpunit --configuration tests/phpunit.xml
  
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
